import{initializeApp}from"https://www.gstatic.com/firebasejs/11.0.2/firebase-app.js";
import{getAuth,onAuthStateChanged,createUserWithEmailAndPassword,signInWithEmailAndPassword,signOut,sendPasswordResetEmail}from"https://www.gstatic.com/firebasejs/11.0.2/firebase-auth.js";
import{getFirestore,doc,getDoc,setDoc,addDoc,collection,query,orderBy,limit,getDocs,serverTimestamp}from"https://www.gstatic.com/firebasejs/11.0.2/firebase-firestore.js";
const firebaseConfig={apiKey:"PASTE_YOUR_FIREBASE_API_KEY",authDomain:"PASTE_YOUR_PROJECT.firebaseapp.com",projectId:"PASTE_YOUR_PROJECT_ID",storageBucket:"PASTE_YOUR_PROJECT.firebasestorage.app",messagingSenderId:"PASTE_YOUR_SENDER_ID",appId:"PASTE_YOUR_APP_ID"};
const app=initializeApp(firebaseConfig),auth=getAuth(app),db=getFirestore(app);let state={user:null,profile:null,role:"buyer",mode:"signup",products:[]};const root=document.getElementById("app");
const cats=[["🍚","Food"],["⛽","Fuel"],["🚌","Transport"],["🧱","Building"],["📱","Electronics"],["👕","Fashion"],["🏠","Home"],["🌾","Agriculture"],["💄","Beauty"],["🔧","Spare Parts"],["📦","Other"],["🗂️","All"]];
const esc=s=>String(s??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[m]));const money=n=>"₦"+Number(n||0).toLocaleString("en-NG");function toast(x){let t=document.getElementById("toast");t.textContent=x;t.style.display="block";setTimeout(()=>t.style.display="none",2200)}
function authScreen(){root.innerHTML=`<div class="screen"><header class="brand-header"><div class="topbar"><div></div><button class="menu-btn" onclick="info()">☰</button></div><div class="hero"><div class="brand">🛒 Naija<span>Price</span></div><p>Check local market prices before you buy</p></div></header><main class="auth-wrap"><div class="card"><h2>👤 Account</h2><div class="role-switch"><button class="${state.role==="buyer"?"active":""}" onclick="role('buyer')">I'm a Buyer</button><button class="${state.role==="seller"?"active":""}" onclick="role('seller')">I'm a Seller</button></div>${state.role==="buyer"?buyerForm():sellerForm()}</div></main></div>`}
function buyerForm(){return `<p class="muted">Create a buyer account or log in to enter the marketplace.</p>${state.mode==="signup"?'<input id="name" class="field" placeholder="Your name">':''}<input id="email" class="field" type="email" placeholder="Email address"><input id="password" class="field" type="password" placeholder="Password"><button class="primary" style="width:100%" onclick="submitAuth()">${state.mode==="login"?"Log In":"Sign Up as Buyer"}</button><p><a href="#" onclick="toggleMode();return false">${state.mode==="login"?"Create a new account":"Already have an account? Log in"}</a></p><p><a href="#" onclick="resetPass();return false">Forgot password?</a></p><div id="msg"></div>`}
function sellerForm(){return `<p class="muted">Seller applications are reviewed before selling is enabled.</p>${state.mode==="signup"?'<input id="name" class="field" placeholder="Full name"><input id="store" class="field" placeholder="Business / store name"><input id="state" class="field" placeholder="State"><input id="city" class="field" placeholder="City / market"><input id="phone" class="field" placeholder="Phone number">':''}<input id="email" class="field" type="email" placeholder="Email address"><input id="password" class="field" type="password" placeholder="Password"><button class="primary" style="width:100%" onclick="submitAuth()">${state.mode==="login"?"Log In":"Apply as Seller"}</button><p><a href="#" onclick="toggleMode();return false">${state.mode==="login"?"Create/apply for an account":"Already have an account? Log in"}</a></p><p><a href="#" onclick="resetPass();return false">Forgot password?</a></p><div id="msg"></div>`}
async function submitAuth(){const email=document.getElementById("email").value.trim(),password=document.getElementById("password").value,msg=document.getElementById("msg");try{if(state.mode==="login"){await signInWithEmailAndPassword(auth,email,password);return}const c=await createUserWithEmailAndPassword(auth,email,password),uid=c.user.uid;if(state.role==="seller")await setDoc(doc(db,"sellers",uid),{uid,email,role:"seller",name:document.getElementById("name").value.trim(),storeName:document.getElementById("store").value.trim(),state:document.getElementById("state").value.trim(),city:document.getElementById("city").value.trim(),phone:document.getElementById("phone").value.trim(),status:"pending",createdAt:serverTimestamp()});else await setDoc(doc(db,"users",uid),{uid,email,role:"buyer",name:document.getElementById("name").value.trim(),status:"active",createdAt:serverTimestamp()})}catch(e){let m="Something went wrong. Please try again.";if(e.code==="auth/email-already-in-use")m="This email is already registered. Please log in.";if(e.code.includes("invalid-credential")||e.code.includes("wrong-password")||e.code.includes("user-not-found"))m="Incorrect email or password. Please try again.";msg.innerHTML=`<div class="error">❌ ${esc(m)}</div>`}}
async function resetPass(){const email=document.getElementById("email")?.value.trim();if(!email)return toast("Enter your email first.");try{await sendPasswordResetEmail(auth,email);toast("Password reset email sent.")}catch(e){toast("We couldn't send the reset email.")}}
async function profile(u){let s=await getDoc(doc(db,"sellers",u.uid));if(s.exists())return s.data();let b=await getDoc(doc(db,"users",u.uid));return b.exists()?b.data():{uid:u.uid,email:u.email,role:"buyer",name:"Buyer"}}
function buyerHome(){root.innerHTML=`<div class="screen"><header class="brand-header"><div class="topbar"><div class="brand">🛒 Naija<span>Price</span></div><button class="menu-btn" onclick="drawer()">☰</button></div></header><main class="market"><div class="location-row">📍<select class="field"><option>All Nigeria</option><option>Benin City, Edo</option><option>Lagos</option><option>Abuja</option><option>Onitsha, Anambra</option><option>Port Harcourt, Rivers</option></select></div><div class="search"><input id="q" class="field" placeholder="Search products, brands or sellers"><button class="primary" onclick="search()">Search</button></div><div class="section-title"><h2>Categories</h2></div><div class="categories">${cats.map(c=>`<button class="cat" onclick="cat('${c[1]}')"><div class="emoji">${c[0]}</div><b>${c[1]}</b></button>`).join("")}</div><div class="section-title"><h2>🔥 Products Near You</h2></div><div id="products" class="products"><div class="empty">Loading products...</div></div><div class="section-title"><h2>👥 Sellers You Follow</h2></div><div class="card"><div class="empty">Follow sellers to see their updates here.</div></div><div class="section-title"><h2>📊 Local Price Intelligence</h2></div><div class="card"><p>Compare local prices and track price history as verified NaijaPrice data grows.</p></div></main><nav class="bottom-nav"><button onclick="scrollTo(0,0)">🏠<br>Home</button><button onclick="document.querySelector('.categories').scrollIntoView()">📂<br>Categories</button><button onclick="toast('Messages coming next')">💬<br>Messages</button><button onclick="toast('Cart coming next')">🛒<br>Cart</button><button onclick="drawer()">👤<br>Account</button></nav></div>`;loadProducts()}
async function loadProducts(){try{const s=await getDocs(query(collection(db,"products"),orderBy("createdAt","desc"),limit(40)));state.products=s.docs.map(d=>({id:d.id,...d.data()}));render(state.products)}catch(e){document.getElementById("products").innerHTML='<div class="empty">No products yet. Verified sellers will appear here.</div>'}}
function render(a){document.getElementById("products").innerHTML=a.length?a.map(x=>`<article class="product"><img src="${esc(x.imageUrl||"https://placehold.co/600x400?text=NaijaPrice")}"><div class="product-body"><span class="badge">✓ Verified Seller</span><h3>${esc(x.name)}</h3><div class="price">${money(x.price)}</div><p class="muted">📍 ${esc(x.location||"Nigeria")}</p><div class="actions"><button class="secondary" onclick="view('${x.id}')">View</button><button class="secondary" onclick="save('${x.id}')">♡ Save</button></div></div></article>`).join(""):'<div class="empty">No products found.</div>'}
function search(){const q=document.getElementById("q").value.toLowerCase();render(state.products.filter(x=>`${x.name||""} ${x.category||""} ${x.location||""} ${x.sellerName||""}`.toLowerCase().includes(q)))}function cat(c){render(c==="All"?state.products:state.products.filter(x=>(x.category||"").toLowerCase()===c.toLowerCase()))}
async function save(id){await setDoc(doc(db,"wishlists",state.user.uid+"_"+id),{userId:state.user.uid,productId:id,createdAt:serverTimestamp()});toast("Saved to wishlist")}
function view(id){const x=state.products.find(p=>p.id===id);if(!x)return;modal(`<button class="close" onclick="closeModal()">×</button><img src="${esc(x.imageUrl||"https://placehold.co/800x500?text=NaijaPrice")}" style="width:100%;border-radius:12px"><h2>${esc(x.name)}</h2><div class="price">${money(x.price)}</div><p>${esc(x.description||"No description provided.")}</p><p>📍 ${esc(x.location||"Nigeria")}</p><button class="primary" style="width:100%" onclick="toast('Seller messaging can be enabled next')">💬 Message Seller</button>`) }
function sellerHome(){const p=state.profile;root.innerHTML=`<div class="screen"><header class="brand-header"><div class="topbar"><div class="brand">🛒 Naija<span>Price</span></div><button class="menu-btn" onclick="drawer()">☰</button></div></header><main class="market"><div class="card"><h2>🏪 ${esc(p.storeName||p.name)}</h2><div class="success">${p.status==="approved"?"🟢 You are a verified seller.":"⏳ Your seller account is pending review. You can list products after approval."}</div><p class="muted">📍 ${esc(p.city||"")} ${esc(p.state||"")}</p></div><h2>Seller Dashboard</h2><div class="categories">${["🛍️ My Store","➕ Add Product","📦 Orders","💬 Messages","👥 Followers","⭐ Reviews"].map(x=>`<button class="cat"><div class="emoji">${x.split(" ")[0]}</div><b>${x.substring(x.indexOf(" ")+1)}</b></button>`).join("")}</div></main></div>`}
function modal(h){const d=document.createElement("div");d.id="modal";d.className="modal";d.innerHTML=`<div class="modal-card">${h}</div>`;document.body.appendChild(d)}function closeModal(){document.getElementById("modal")?.remove()}function drawer(){const d=document.createElement("div");d.id="drawer";d.className="drawer";d.innerHTML=`<aside class="drawer-panel"><button onclick="document.getElementById('drawer').remove()">✕ Close</button><h2>Account</h2><p><b>${esc(state.profile?.name||state.profile?.storeName)}</b><br>${esc(state.profile?.email)}</p><button>❤️ Wishlist</button><button>👥 Following</button><button>💬 Messages</button><button>🛒 Cart</button><button>🔔 Notifications</button><button>⚙️ Settings</button><button onclick="logout()">🚪 Log Out</button></aside>`;document.body.appendChild(d)}async function logout(){await signOut(auth)}function info(){modal(`<button class="close" onclick="closeModal()">×</button><h2>NaijaPrice</h2><p>Discover products, compare Nigerian prices and find trusted sellers.</p>`)}
window.role=r=>{state.role=r;state.mode="signup";authScreen()};window.toggleMode=()=>{state.mode=state.mode==="login"?"signup":"login";authScreen()};window.submitAuth=submitAuth;window.resetPass=resetPass;window.search=search;window.cat=cat;window.view=view;window.save=save;window.drawer=drawer;window.logout=logout;window.info=info;window.closeModal=closeModal;
onAuthStateChanged(auth,async u=>{state.user=u;if(!u){state.profile=null;authScreen();return}state.profile=await profile(u);state.role=state.profile.role||"buyer";state.role==="seller"?sellerHome():buyerHome()});
                                                               
